routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\Customer\DashboardController::class, 'index'])->name('customer.dashboard');
Route::get('/home', [App\Http\Controllers\Customer\DashboardController::class, 'index'])->name('home');
Route::get('/signin', [App\Http\Controllers\Customer\AccountController::class, 'signin'])->name('customer.signin');
Route::post('/signup', [App\Http\Controllers\Customer\AccountController::class, 'signup'])->name('customer.signup');
Route::get('/produk/{id}', [App\Http\Controllers\Customer\DashboardController::class, 'detailProduk']);
Auth::routes();

Route::middleware(['auth'])->group(
    function () {

        Route::resource('customer-cart', App\Http\Controllers\Customer\CartController::class);
        Route::get('/checkout', [App\Http\Controllers\Customer\CheckoutController::class, 'index']);
        Route::post('/check_ongkir', [App\Http\Controllers\Customer\CheckoutController::class, 'check_ongkir']);
        Route::post('/payment', [App\Http\Controllers\Customer\CheckoutController::class, 'bayarSekarang']);
        Route::get('/customer-transaksi', [App\Http\Controllers\Customer\TransaksiController::class, 'index']);
        Route::get('/customer-transaksi/{id}', [App\Http\Controllers\Customer\TransaksiController::class, 'show']);
        Route::post('/payment_midtrains', [App\Http\Controllers\Customer\CheckoutController::class, 'paymentProsess']);

        // user admin
        Route::prefix('/admin')->group(function () {

            // dashboard
            Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
            Route::post('/dashboard/statistik', [App\Http\Controllers\Admin\DashboardController::class, 'statistik'])->name('admin.dashboard-statistik');
            Route::post('/dashboard/chart1', [App\Http\Controllers\Admin\DashboardController::class, 'chart1'])->name('admin.dashboard-chart1');
            Route::post('/dashboard/chart2', [App\Http\Controllers\Admin\DashboardController::class, 'chart2'])->name('admin.dashboard-chart2');

            // menu laporan
            // laporan transaksi
            Route::get('/laporan-trx', [App\Http\Controllers\Admin\LaporanController::class, 'indexTrx'])->name('admin.laporan-transaksi');
            Route::get('/laporan-stk', [App\Http\Controllers\Admin\LaporanController::class, 'indexStok'])->name('admin.laporan-stok');

            // menu transaksi
            // transaksi
            Route::get('/transaksi', [App\Http\Controllers\Admin\TransaksiController::class, 'index'])->name('admin.transaksi');
            Route::post('/transaksi/detail', [App\Http\Controllers\Admin\TransaksiController::class, 'detail']);
            Route::get('/transaksi/{id}/edit', [App\Http\Controllers\Admin\TransaksiController::class, 'edit']);
            Route::post('/transaksi/hapus', [App\Http\Controllers\Admin\TransaksiController::class, 'destroy'])->name('admin.transaksi-hapus');

            // preorder
            Route::get('/preorder', [App\Http\Controllers\Admin\PreOrderController::class, 'index'])->name('admin.preorder');
            Route::post('/preorder/detail', [App\Http\Controllers\Admin\PreOrderController::class, 'detail']);
            Route::get('/preorder/{id}/edit', [App\Http\Controllers\Admin\PreOrderController::class, 'edit']);
            Route::post('/preorder/kirim', [App\Http\Controllers\Admin\PreOrderController::class, 'update'])->name('admin.preorder-update');
            Route::post('/preorder/hapus', [App\Http\Controllers\Admin\PreOrderController::class, 'destroy'])->name('admin.preorder-hapus');

            // pengiriman
            Route::get('/pengiriman', [App\Http\Controllers\Admin\PengirimanController::class, 'index'])->name('admin.pengiriman');
            Route::get('/pengiriman/{id}/edit', [App\Http\Controllers\Admin\PengirimanController::class, 'edit']);
            Route::post('/pengiriman/kirim', [App\Http\Controllers\Admin\PengirimanController::class, 'kirim'])->name('admin.pengiriman-kirim');

            // menu informasi
            // alamat toko
            Route::get('/alamat-toko', [App\Http\Controllers\Admin\AlamatTokoController::class, 'index'])->name('admin.alamat-toko');
            Route::get('/alamat-toko/edit', [App\Http\Controllers\Admin\AlamatTokoController::class, 'edit']);
            Route::post('/alamat-toko/update', [App\Http\Controllers\Admin\AlamatTokoController::class, 'update'])->name('admin.alamat-toko-update');

            // review
            Route::get('/review', [App\Http\Controllers\Admin\ReviewController::class, 'index'])->name('admin.review');
            Route::get('/review/{id}/edit', [App\Http\Controllers\Admin\ReviewController::class, 'edit']);
            Route::post('/review/hapus', [App\Http\Controllers\Admin\ReviewController::class, 'destroy'])->name('admin.review-hapus');

            // event
            Route::get('/event', [App\Http\Controllers\Admin\EventController::class, 'index'])->name('admin.event');
            Route::post('/event/tambah', [App\Http\Controllers\Admin\EventController::class, 'store'])->name('admin.event-tambah');
            Route::get('/event/{id}/edit', [App\Http\Controllers\Admin\EventController::class, 'edit']);
            Route::post('/event/hapus', [App\Http\Controllers\Admin\EventController::class, 'destroy'])->name('admin.event-hapus');
            Route::post('/event/update', [App\Http\Controllers\Admin\EventController::class, 'update'])->name('admin.event-update');

            // menu gudang
            // barang
            Route::get('/barang', [App\Http\Controllers\Admin\BarangController::class, 'index'])->name('admin.barang');
            Route::post('/barang/tambah', [App\Http\Controllers\Admin\BarangController::class, 'store'])->name('admin.barang-tambah');
            Route::get('/barang/{id}/edit', [App\Http\Controllers\Admin\BarangController::class, 'edit']);
            Route::post('/barang/hapus', [App\Http\Controllers\Admin\BarangController::class, 'destroy'])->name('admin.barang-hapus');
            Route::post('/barang/tampilkan', [App\Http\Controllers\Admin\BarangController::class, 'tampilkan'])->name('admin.barang-tampilkan');

            // foto-produk
            Route::get('/foto-produk', [App\Http\Controllers\Admin\FotoProdukController::class, 'index'])->name('admin.foto-produk');
            Route::post('/foto-produk/tambah', [App\Http\Controllers\Admin\FotoProdukController::class, 'store'])->name('admin.foto-produk-tambah');
            Route::get('/foto-produk/{id}/edit', [App\Http\Controllers\Admin\FotoProdukController::class, 'edit']);
            Route::post('/foto-produk/hapus', [App\Http\Controllers\Admin\FotoProdukController::class, 'destroy'])->name('admin.foto-produk-hapus');

            // stok
            Route::get('/stok', [App\Http\Controllers\Admin\BarangController::class, 'indexStok'])->name('admin.stok');

            // menu master
            // kategori
            Route::get('/kategori', [App\Http\Controllers\Admin\KategoriController::class, 'index'])->name('admin.kategori');
            Route::post('/kategori/tambah', [App\Http\Controllers\Admin\KategoriController::class, 'store'])->name('admin.kategori-tambah');
            Route::get('/kategori/{id}/edit', [App\Http\Controllers\Admin\KategoriController::class, 'edit']);
            Route::post('/kategori/hapus', [App\Http\Controllers\Admin\KategoriController::class, 'destroy'])->name('admin.kategori-hapus');

            // user
            Route::get('/user', [App\Http\Controllers\Admin\UserController::class, 'index'])->name('admin.user');
            Route::post('/user/tambah', [App\Http\Controllers\Admin\UserController::class, 'store'])->name('admin.user-tambah');
            Route::get('/user/{id}/edit', [App\Http\Controllers\Admin\UserController::class, 'edit']);
            Route::post('/user/hapus', [App\Http\Controllers\Admin\UserController::class, 'destroy'])->name('admin.user-hapus');
            Route::patch('/user/update', [App\Http\Controllers\Admin\UserController::class, 'update'])->name('admin.user-update');

            // about
            Route::get('/about', function () {
                return view('about');
            })->name('about');
        });


        Route::get('/account', [App\Http\Controllers\Customer\AccountController::class, 'index'])->name('customer.account');
        Route::post('/update_akun', [App\Http\Controllers\Customer\AccountController::class, 'updateAkun']);
        Route::post('/store_review', [App\Http\Controllers\Customer\DashboardController::class, 'storeReview']);
        Route::get('/konfirmasi_pembayaran/{orderId}', [App\Http\Controllers\Customer\TransaksiController::class, 'konfirmasiPembayaran']);
        Route::get('/konfirmasi-barang-sampai/{orderId}', [App\Http\Controllers\Customer\TransaksiController::class, 'konfirmasi']);
        Route::post('/store_brg_sampai/{orderId}', [App\Http\Controllers\Customer\TransaksiController::class, 'konfirmasiBarangSampai']);

        Route::resource('pre-order', App\Http\Controllers\Customer\PreOrderController::class);
        Route::post('finish-pre-order', [App\Http\Controllers\Customer\PreOrderController::class, 'finishOrder']);
        Route::post('batal-pre-order/{id}', [App\Http\Controllers\Customer\PreOrderController::class, 'batalPreOrder']);
        Route::post('billing-address-pre-order', [App\Http\Controllers\Customer\PreOrderController::class, 'billingPreOrder']);

app/Http/Controllers/Customer/AccountController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Alert;
use Illuminate\Support\Facades\Hash;
use App\Models\Province;
use App\Models\City;
use App\Models\User;
use App\Models\AlamatUser;
use Validator;

class AccountController extends Controller
{

    public function index()
    {
        $provinces = Province::all();
        $user = User::join('alamat_user as alamat', 'alamat.id', '=', 'users.alamat_user_id')
            ->where('users.id', \Auth::user()->id)
            ->select('users.*', 'alamat.province_id', 'alamat.city_id', 'alamat.kode_pos', 'alamat.alamat')
            ->first();
        $cities = City::select('city_id as id', 'name')
            ->get();
        return view('customer.account.index', compact('user', 'provinces', 'cities'));
    }

    public function updateAkun(Request $request)
    {
        $current_password = $request->current_password;
        $password_baru = $request->password;
        $password_lama = $request->password_confirmation;
        $user = User::find(\Auth::user()->id);
        if (Hash::check($current_password, $user->password)) {
            if ($password_baru != "") {
                if ($password_baru != $password_lama) {
                    Alert::error('Gagal', 'Password Baru dengan Konfirmasi Password Tidak Sama');
                    return redirect()->back();
                }
                $user->password = Hash::make($password_baru);
            } else {
                $user->name = $request->name;
                $user->email = $request->email;
                $user->telepon = $request->telepon;
                $user->username = $request->username;
                $user->save();

                $alamat = AlamatUser::find($user->alamat_user_id);
                $alamat->province_id = $request->province_id;
                $alamat->city_id = $request->city_id;
                $alamat->kode_pos = $request->kode_pos;
                $alamat->alamat = $request->alamat;
                $alamat->save();
                Alert::success('Sukses', 'Berhasil mengubah data user');
                return redirect()->back();
            }
        } else {
            Alert::error('Gagal', 'Password anda tidak cocok dengan password anda login');
            return redirect()->back();
        }
    }

    public function signin()
    {
        $provinces = Province::all();
        return view('customer.account.signin', compact('provinces'));
    }

    public function getCities(Request $request)
    {
        $search = $request->search;
        $provinsi = $request->provinsi;
        if ($search != "") {
            $cities = City::where('province_id', $provinsi)
                ->where('name', 'like', '%' . $search . '%')
                ->select('city_id as id', 'name')
                ->get();
        } else {
            $cities = City::where('province_id', $provinsi)
                ->select('city_id as id', 'name')
                ->get();
        }
        return response()->json($cities);
    }

    public function signup(Request $request)
    {

        $rules = [
            'name'                   => 'required|unique:users,name',
            'email'                 => 'required|unique:users,email',
            'username'                 => 'required|unique:users,username',
            'telepon'                 => 'required|unique:users,telepon'
        ];

        $messages = [
            'name.unique'              => 'Nama Lengkap Sudah Terdaftar',
            'name.required'            => 'Nama Lengkap Wajib Diisi',
            'email.unique'            => 'Email Sudah Terdaftar',
            'email.required'            => 'Email Wajib Diisi',
            'username.unique'            => 'Username Sudah Terdaftar',
            'username.required'            => 'Username Wajib Diisi',
            'telepon.unique'            => 'No. Telepon Sudah Terdaftar',
            'telepon.required'            => 'No. Telepon Wajib Diisi',
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($request->all);
        }

        $alamat = new AlamatUser();
        $alamat->province_id = $request->province_id;
        $alamat->city_id = $request->city_id;
        $alamat->kode_pos = $request->kode_pos;
        $alamat->alamat = $request->alamat;
        $alamat->save();

        DB::table('users')->insert([
            'name'  => $request->name,
            'username'  => $request->username,
            'telepon'  => $request->telepon,
            'alamat_user_id'  => $alamat->id,
            'email'  => $request->email,
            'password'  => Hash::make($request->password),
            'role'  => 'customer',
            'status'    => '0'
        ]);

        Alert::success('Sukses', 'Berhasil Mendaftar Akun');
        return redirect()->back();
    }
}

app/Http/Controllers/Customer/CartController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cartItems = \Cart::getContent();
        return view('customer.cart', compact('cartItems'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Cart::add([
            'id' => $request->id,
            'name' => $request->namaProduk,
            'price' => $request->hargaProduk,
            'quantity' => $request->jumlahProduk,
            'attributes' => array(
                'image' => $request->gambarProduk,
                'weight' => $request->beratProduk
            )
        ]);
        return redirect('customer-cart')->with('success', 'Data Berhasil Dimasukkan ke Keranjang');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \Cart::update(
            $id,
            [
                'quantity' => [
                    'relative' => false,
                    'value' => $request->jumlahProduk
                ],
            ]
        );
        return redirect('customer-cart')->with('success', 'Data Keranjang Berhasil Diperbaruhi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \Cart::remove($id);
        return redirect('customer-cart')->with('success', 'Data Keranjang Berhasil Dihapus');
    }
}

resources/views/customer/cart.blade.php
@extends('layouts.landing')
@section('content')
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <h1>Karanjang Produk</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="cart-section mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="cart-table-wrap">
                    <table class="cart-table">
                        <thead class="cart-table-head">
                            <tr class="table-head-row">
                                <th class="product-remove"></th>
                                <th class="product-image">Foto</th>
                                <th class="product-name">Nama Produk</th>
                                <th class="product-price">Berat</th>
                                <th class="product-price">Harga</th>
                                <th class="product-quantity">Qty</th>
                                <th class="product-quantity">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($cartItems as $item)
                            <tr class="table-body-row">
                                <td class="product-remove">
                                    <form action="{{ route('customer-cart.destroy', $item->id) }}" method="POST">
                                        @csrf
                                        {{ method_field('delete') }}
                                        <button type="submit" class="btn btn-danger text-white">
                                            <span class="fa fa-trash"></span>
                                        </button>
                                    </form>
                                </td>
                                <td class="product-image"><img src="{{ asset('foto/produk/'.$item->attributes->image) }}" alt=""></td>
                                <td class="product-name">{{ $item->name }}</td>
                                <td class="product-name">{{ $item->attributes->weight }} gram</td>
                                <td class="product-price">{{ rupiah($item->price) }}</td>
                                <td class="product-quantity p-2">
                                    <form action="{{ route('customer-cart.update', $item->id) }}" method="POST">
                                        @csrf
                                        {{ method_field('put') }}
                                        <div class="input-group mb-3">
                                            <input type="number" name="jumlahProduk" class="form-control" placeholder="0" value="{{ $item->quantity }}">
                                            <div class="input-group-append">
                                              <button type="submit" class="btn btn-warning">Update</button>
                                            </div>
                                        </div>
                                    </form>
                                </td>
                                <td class="product-price">{{ rupiah($item->price * $item->quantity ) }}</td>
                            </tr>
                            @endforeach
                            <tr>
                                <td colspan="6" class="product-name">Sub Total</td>
                                <td class="product-price">{{ rupiah(Cart::getTotal())  }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="row justify-content-end mt-3">
                        <a href="{{ url('/') }}" class="beli-btn mr-2">Belanja Lagi</a>
                        <a href="{{ url('checkout') }}" class="boxed-btn black">Check Out</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/customer/pre-order.blade.php
@extends('layouts.landing')
@section('content')
    <div class="breadcrumb-section breadcrumb-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 text-center">
                    <div class="breadcrumb-text">
                        <h1>Pre Order</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="checkout-section mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card card-body">
                        <div class="mb-3">
                            <a href="{{ route('pre-order.create') }}" class="btn btn-primary p-2">Buat Pesanan</a>
                        </div>
                        <div class="table-responsive">
                            <table class="table" id="tablePreOrder" style="width: 100%">
                                <thead>
                                    <tr>
                                        <td>No</td>
                                        <td>Kode Pesanan</td>
                                        <td>Tanggal</td>
                                        <td>Status</td>
                                        <td>Aksi</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $no = 0; @endphp
                                    @foreach ($preOrder as $row)
                                        @php $no++; @endphp
                                        <tr>
                                            <td>{{ $no }}</td>
                                            <td>{{ $row->kode_pesanan }}</td>
                                            <td>{{ $row->created_at }}</td>
                                            <td>
                                                @if ($row->status == 0)
                                                    Menunggu Verifikasi
                                                @elseif($row->status == 1)
                                                    Terverfikasi & Menunggu Pembayaran
                                                @elseif($row->status == 2)
                                                    Terverfikasi & Terbayar
                                                @elseif($row->status == 3)
                                                    Dibatalkan
                                                @endif
                                            </td>
                                            <td>
                                                @if ($row->status != 3 && $row->status != 2)
                                                    <button type="button" data-toggle="modal"
                                                        data-target="#modalBatal{{ $row->id }}" class="btn btn-danger">
                                                        Batalkan
                                                    </button>
                                                @endif
                                                <a class="btn btn-info" href="{{ route('pre-order.show', $row->kode_pesanan) }}">Detail</a>
                                            </td>
                                        </tr>

                                        <div class="modal fade" id="modalBatal{{ $row->id }}" tabindex="-1"
                                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Konfirmasi</h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Apakah yakin membatalkan pre order {{ $row->kode_pesanan }}  ?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary"
                                                            data-dismiss="modal">Tidak</button>
                                                        <form action="{{ url('batal-pre-order/'.$row->id) }}"
                                                            method="post">
                                                            @csrf
                                                            <button type="submit" class="btn btn-primary">Ya</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $("#tablePreOrder").DataTable();
    </script>
@endpush